# Generated by Django 3.1.12 on 2021-08-21 06:56

import API.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', djongo.models.fields.ArrayField(model_container=API.models.PizzaType)),
                ('size', djongo.models.fields.ArrayField(model_container=API.models.PizzaSize)),
                ('veg', models.BooleanField(default=True)),
                ('defaultTopping', djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='topping', to='API.topping')),
            ],
        ),
    ]
